# Generated by Django 3.2.16 on 2024-12-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_tlg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tlg_id',
            field=models.PositiveBigIntegerField(db_index=True, null=True, verbose_name='ID диалога пользователя'),
        ),
    ]
